/// <reference path="../../index.d.ts" />

// Entry point for the Tizen build. In a full build this file is generated by
// the bundler (tools/bundle.mjs) which wires the Tizen adapter to the core.
import { Agent } from "@tv-ai-agent/core";
import { createTizenAdapter } from "@tv-ai-agent/adapter-tizen";
import { createOpenAiCompatibleClient } from "@tv-ai-agent/llm-connectors";

async function boot() {
  const platform = createTizenAdapter();
  await platform.init();

  const llm = createOpenAiCompatibleClient({
    // On-device: point at a localhost inference server; cloud: your gateway.
    baseUrl: window.__AGENT_LLM_BASE_URL__ || "http://127.0.0.1:8080/v1",
    model: window.__AGENT_LLM_MODEL__ || "local-tv-agent",
  });

  const agent = new Agent({ platform, llm });
  window.__tvAgent = agent; // expose for the UI shell / voice pipeline
  document.getElementById("status").textContent =
    `Ready on ${platform.device.model} (${platform.device.soc})`;
}
boot().catch((e) => {
  document.getElementById("status").textContent = "Boot error: " + e.message;
});
